/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author kpaiv
 */
public class NumberGenius extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NumberGenius.class.getName());

    /**
     * Creates new form NumberGenius
     */
    public NumberGenius() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGeniumQuestion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spnGuess = new javax.swing.JSpinner();
        btnLuckButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtGeniumQuestion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGeniumQuestion.setText("<html>Adivinhe em qual numero<br>  estou pensando</html>");
        getContentPane().add(txtGeniumQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/DialogBalloon.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 314, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/Genium.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Sugerir numero:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        spnGuess.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnGuess, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, 30));

        btnLuckButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLuckButton.setText("Adivinhar");
        btnLuckButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLuckButton.addActionListener(this::btnLuckButtonActionPerformed);
        getContentPane().add(btnLuckButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuckButtonActionPerformed
        // TODO add your handling code here:
        // 1. O Gênio sorteia um número de 1 a 5
        // A conta é: (valor_inicial + Math.random() * (valor_final - valor_inicial + 1))
        double aleatorio = 1 + Math.random() * 5;
        
        /*Math.random gera um numero quebrado porém como queremos numeros exatos, convertemos para um inteiro, que apenas ignora
        os numeros após a virgula, o (int) força o codigo a gerar um inteiro*/
        int numGenio = (int) aleatorio;

        // 2. Pegamos o palpite do Spinner.
        int seuPalpite = (int) spnGuess.getValue();
        
        //se o palpite do spinner for o mesmo que o numero gerado, informamos uma mensagem, se não, informamos a outra.
        if (numGenio == seuPalpite) {
            txtGeniumQuestion.setText("<html><b>ACERTOU!</b><br>Eu realmente pensei no " + numGenio + "</html>" );
        } else {
            txtGeniumQuestion.setText("<html><b>ERROU!</b><br>Eu pensei no " + numGenio + ", não no " + seuPalpite + "</html>");
        }
    }//GEN-LAST:event_btnLuckButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NumberGenius().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnLuckButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner spnGuess;
    private javax.swing.JLabel txtGeniumQuestion;
    // End of variables declaration//GEN-END:variables
}
